version: '3.8'

services:
  app:
    container_name: app-dev-container
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: eggforce-sc-dev.local
    working_dir: /workspace
    volumes:
      - ..:/workspace
    command: sleep infinity
