---
name: nightly-scheduled-test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs every day at midnight
    - cron: "0 0 * * *"

jobs:
  nightly-make-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
      - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c #v1.4.0

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential wabt

      - name: Setup
        run: make prepare
      
      - name: Run build-contracts
        run: make build-contract

      - name: Run tests
        run: make prepare-test test
